import type { QuestTemplate } from "@tactix/shared";
import { Game, MatchMode, SkillDomain } from "@tactix/shared";

export const QUEST_TEMPLATES: QuestTemplate[] = [
  // ─── Aim Quality ────────────────────────────────────────────────
  {
    id: "cs2_hs_rate",
    domain: "AIM_QUALITY",
    title: "Clean taps",
    description: "Hit a strong headshot rate today.",
    criteria: { type: "rate", numerator: "headshots", denominator: "kills", op: ">=", target: 0.32, game: "CS2", mode: "ALL", minDenominator: 20 },
    eligibleGames: ["CS2"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },
  {
    id: "mr_damage",
    domain: "AIM_QUALITY",
    title: "Damage discipline",
    description: "Put up meaningful damage without feeding.",
    criteria: { type: "aggregate", metric: "damageDealt", op: ">=", target: 25_000, game: "MARVEL_RIVALS", mode: "ALL" },
    eligibleGames: ["MARVEL_RIVALS"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },
  {
    id: "val_hs_rate",
    domain: "AIM_QUALITY",
    title: "Crosshair placement",
    description: "Land a high headshot percentage today.",
    criteria: { type: "rate", numerator: "headshots", denominator: "kills", op: ">=", target: 0.25, game: "VALORANT", mode: "ALL", minDenominator: 15 },
    eligibleGames: ["VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },
  {
    id: "val_damage_output",
    domain: "AIM_QUALITY",
    title: "Combat score",
    description: "Deal strong damage across your matches today.",
    criteria: { type: "aggregate", metric: "damage", op: ">=", target: 3000, game: "VALORANT", mode: "ALL" },
    eligibleGames: ["VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 0.8,
  },

  // ─── First Engagement ──────────────────────────────────────────
  {
    id: "cs2_opening_duel",
    domain: "FIRST_ENGAGEMENT",
    title: "Win first contact",
    description: "Tilt the round by winning early fights.",
    criteria: { type: "rate", numerator: "firstEngagementWins", denominator: "firstEngagementTotal", op: ">=", target: 0.55, game: "CS2", mode: "ALL", minDenominator: 10 },
    eligibleGames: ["CS2"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },
  {
    id: "mr_low_early_deaths",
    domain: "FIRST_ENGAGEMENT",
    title: "Stay alive early",
    description: "Avoid early pick-offs; keep deaths low.",
    criteria: { type: "aggregate", metric: "deaths", op: "<=", target: 18, game: "MARVEL_RIVALS", mode: "ALL" },
    eligibleGames: ["MARVEL_RIVALS"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 0.7,
  },
  {
    id: "val_high_kill_game",
    domain: "FIRST_ENGAGEMENT",
    title: "Pop off",
    description: "Hit a high kill count in at least one match today.",
    criteria: { type: "perMatch", metric: "kills", op: ">=", target: 20, minMatches: 1, game: "VALORANT", mode: "ALL" },
    eligibleGames: ["VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },

  // ─── Survival Quality ──────────────────────────────────────────
  {
    id: "universal_deaths_cap",
    domain: "SURVIVAL_QUALITY",
    title: "Trade your life smarter",
    description: "Keep deaths under control today.",
    criteria: { type: "aggregate", metric: "deaths", op: "<=", target: 20, game: null, mode: "ALL" },
    eligibleGames: ["CS2", "MARVEL_RIVALS", "VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },
  {
    id: "universal_kd_positive",
    domain: "SURVIVAL_QUALITY",
    title: "Positive impact",
    description: "Finish the day with a positive K/D.",
    criteria: { type: "rate", numerator: "kills", denominator: "deaths", op: ">=", target: 1.05, game: null, mode: "ALL", minDenominator: 15 },
    eligibleGames: ["CS2", "MARVEL_RIVALS", "VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },
  {
    id: "val_damage_efficiency",
    domain: "SURVIVAL_QUALITY",
    title: "Smart aggression",
    description: "Deal more damage than you take today.",
    criteria: { type: "rate", numerator: "damage", denominator: "damageReceived", op: ">=", target: 1.2, game: "VALORANT", mode: "ALL", minDenominator: 500 },
    eligibleGames: ["VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 0.8,
  },

  // ─── Objective Impact ──────────────────────────────────────────
  {
    id: "cs2_plants_defuses",
    domain: "OBJECTIVE_IMPACT",
    title: "Touch the objective",
    description: "Get involved on plants/defuses today.",
    criteria: { type: "aggregate", metric: "plants", op: ">=", target: 2, game: "CS2", mode: "ALL" },
    eligibleGames: ["CS2"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 0.8,
  },
  {
    id: "mr_objective_time",
    domain: "OBJECTIVE_IMPACT",
    title: "Play the point",
    description: "Bank real objective time today.",
    criteria: { type: "aggregate", metric: "objectiveTimeSeconds", op: ">=", target: 120, game: "MARVEL_RIVALS", mode: "ALL" },
    eligibleGames: ["MARVEL_RIVALS"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },
  {
    id: "val_round_impact",
    domain: "OBJECTIVE_IMPACT",
    title: "Round MVP",
    description: "Average a high combat score per round.",
    criteria: { type: "rate", numerator: "score", denominator: "roundsPlayed", op: ">=", target: 220, game: "VALORANT", mode: "ALL", minDenominator: 20 },
    eligibleGames: ["VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },
  {
    id: "cr_crowns",
    domain: "OBJECTIVE_IMPACT",
    title: "Crown collector",
    description: "Earn crowns in Clash Royale battles.",
    criteria: { type: "aggregate", metric: "crowns", op: ">=", target: 10, game: "CLASH_ROYALE", mode: "ALL" },
    eligibleGames: ["CLASH_ROYALE"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },

  // ─── Utility Intent ────────────────────────────────────────────
  {
    id: "cs2_flash_assists",
    domain: "UTILITY_INTENT",
    title: "Set up a teammate",
    description: "Convert utility into openings.",
    criteria: { type: "aggregate", metric: "flashAssists", op: ">=", target: 2, game: "CS2", mode: "ALL" },
    eligibleGames: ["CS2"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 0.8,
  },
  {
    id: "mr_assists_or_heal",
    domain: "UTILITY_INTENT",
    title: "Enable the team",
    description: "Rack up assists/heals that win fights.",
    criteria: { type: "aggregate", metric: "assists", op: ">=", target: 18, game: "MARVEL_RIVALS", mode: "ALL" },
    eligibleGames: ["MARVEL_RIVALS"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 0.8,
  },
  {
    id: "val_assists",
    domain: "UTILITY_INTENT",
    title: "Team player",
    description: "Generate assists through ability usage and intel.",
    criteria: { type: "aggregate", metric: "assists", op: ">=", target: 15, game: "VALORANT", mode: "ALL" },
    eligibleGames: ["VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 0.8,
  },

  // ─── Consistency ───────────────────────────────────────────────
  {
    id: "universal_play_2_matches",
    domain: "CONSISTENCY",
    title: "Show up",
    description: "Play at least 2 matches today.",
    criteria: { type: "aggregate", metric: "matchesPlayed", op: ">=", target: 2, game: null, mode: "ALL" },
    eligibleGames: ["CS2", "MARVEL_RIVALS", "VALORANT", "CLASH_ROYALE"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 1,
  },
  {
    id: "universal_kills_floor",
    domain: "CONSISTENCY",
    title: "Baseline output",
    description: "Hit a steady kill count today.",
    criteria: { type: "aggregate", metric: "kills", op: ">=", target: 25, game: null, mode: "ALL" },
    eligibleGames: ["CS2", "MARVEL_RIVALS", "VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 0.8,
  },
  {
    id: "val_consistent_score",
    domain: "CONSISTENCY",
    title: "Steady performer",
    description: "Average a solid score across matches today.",
    criteria: { type: "rate", numerator: "score", denominator: "matchesPlayed", op: ">=", target: 4000, game: "VALORANT", mode: "ALL", minDenominator: 2 },
    eligibleGames: ["VALORANT"],
    eligibleModes: ["ALL", "RANKED", "UNRANKED"],
    weight: 0.7,
  },

  // ─── Generic / Any Game ────────────────────────────────────────
  {
    id: "generic_playtime",
    domain: "CONSISTENCY",
    title: "Dedication",
    description: "Log active playtime in any supported game.",
    criteria: { type: "aggregate", metric: "durationSeconds", op: ">=", target: 1800, game: null, mode: "ALL" },
    eligibleGames: ["CS2", "MARVEL_RIVALS", "VALORANT", "CLASH_ROYALE"],
    eligibleModes: ["ALL"],
    weight: 0.5,
  },
];
